---
# tasks file for ansible-role-add-dns-host

- name: Add DNS Record
  win_shell: |
    Add-DnsServerResourceRecordA -Name {{ item.Name }} -ZoneName {{ item.ZoneName }} -IPv4Address {{ item.IP }}
  register: output
  loop: '{{dns_hosts}}'

- name: Display output
  debug:
    var: output

