---
# tasks file for ansible-role-add-dns-host

- name: Add DNS Record
  win_shell: |
    Add-DnsServerResourceRecordA -Name {{ item.Name }} -ZoneName {{ item.ZoneName }} -IPv4Address {{ item.IP }}
  loop: '{{dns_hosts}}'

